### ISSUE TITLE
GPU and Machine Specifications for Reproducing Results

### ISSUE THREAD

**Issue by Venseven** [shuyanzhou/docprompting#12]
Hello
I am currently working on replicating the results presented in your paper. I came across the information that you utilized an A6000 GPU for your experiments. Could you kindly provide additional details about the GPU's memory capacity and the overall specifications of the machine used?

**Comment by shuyanzhou** [comment]
Hi @Venseven, an A6000 GPU has ~48GB memory. I did not look into the machine specification very carefully. However, using a machine with 24GB memory is often more than enough.
