### ISSUE TITLE
api document dataset request

### ISSUE THREAD

**Issue by middle-chunjie** [shuyanzhou/docprompting#15]
I gained a lot from reading your research work. I am very interested in the process of collecting API information from the devdocs website mentioned in your article. I also noticed that the data set you finally open-sourced includes information about data analysis (APIs of third-party libraries such as numpy and pandas). However, I am still confused about the process of collecting the data set. Can you provide further explanation on how you collected the data (do you need to crawl devdocs or install any specific project)?
I hope to receive your reply, as it will be very helpful to me.

**Comment by shuyanzhou** [comment]
Thanks for your interest! 

> How you collected the data

We collected the docs by crawling devdocs. Let me see if I could still find the script

**Comment by middle-chunjie** [comment]
> Thanks for your interest!
> 
> > How you collected the data
> 
> We collected the docs by crawling devdocs. Let me see if I could still find the script

Thank you again for your reply. If you can provide relevant scripts, it will be very helpful to me because I noticed that the devdocs open-source project mainly uses Ruby language for document crawling, which is a huge challenge for me.

**Comment by shuyanzhou** [comment]
Pasting the email reply here in case it is useful to others:

> To get devdocs, they have actual dumps available at this url: https://downloads.devdocs.io/<library_path>.tar.gz where <library_path> refers to the actual library in devdocs.
> For example, to download this document: https://devdocs.io/angular~15/, you could simply download https://downloads.devdocs.io/angular~15.tar.gz
