### ISSUE TITLE
Which python version should be used

### ISSUE THREAD

**Issue by ShiminZhang** [shuyanzhou/docprompting#17]
Hi, 

I was trying to install the envrionment from requirement.txt, but some packages seems not compatible with python3.11.
Which version did you use?

Thanks from newbie XD

**Comment by shuyanzhou** [comment]
Hi,

If I remember correctly, we used `python 3.8`. Let me know if it works

**Comment by ShiminZhang** [comment]
Hi,

Thanks for the reply.

None of {3.8 3.9 3.10} works for me when me attempting to install requirements. mkl-fft==1.3.0 requires Python>=3.10, while I keep getting errors when installing astropy==4.2.1 on Python3.10.

anw, I managed to just use my local environment instead of installing the requirement.txt. Don't bother. XD

Thanks~

**Comment by odysseyhuang** [comment]
I met this problem too,  fail to install all the requirements provided, could you kindly provide detailed guidance on how to resolve this?
