### ISSUE TITLE
Could you share the prompts for Codex that use static examples for both CoNaLa and TLDR?

### ISSUE THREAD

**Issue by ziansu** [shuyanzhou/docprompting#2]
I only found the prompt for TLDR in `utils/constants.py` but it is not consistent with table 7 in the paper.

**Comment by shuyanzhou** [comment]
Sorry for the confusion. The prompts in `utils/constants.py` are out-dated. Reported results are with the prompts listed in the paper.

**Comment by shuyanzhou** [comment]
The prompts on different settings have been updated here: https://github.com/shuyanzhou/docprompting/tree/main/prompts

**Comment by ziansu** [comment]
> The prompts on different settings have been updated here: https://github.com/shuyanzhou/docprompting/tree/main/prompts

Thank you for the update!

Still, I have a small question regarding how the three examples are selected for the prompt. Are they selected randomly or based on some strategies?

**Comment by shuyanzhou** [comment]
I basically randomly browsed some examples from the training set and selected three examples where *intuitively*, the retrieved documentation will be helpful.
