### ISSUE TITLE
Can not  reproduce your result.

### ISSUE THREAD

**Issue by JiexingQi** [shuyanzhou/docprompting#5]
Hi, @shuyanzhou , you did a great work. I'm recently want to reproduce your code and I just follow your instructions on Readme.md use the following command 
```
ds='conala'
python generator/fid/test_reader_simple.py \
    --model_path models/generator/${ds}.fid.codet5.top10/checkpoint/best_dev/best_dev \
    --tokenizer_name models/generator/codet5-base \
    --eval_data data/${ds}/fid.cmd_test.codet5.t10.json \
    --per_gpu_batch_size 8 \
    --n_context 10 \
    --name ${ds}.fid.codet5.top10 \
    --checkpoint_dir models/generator  \
    --result_tag test_same \
    --main_port 81692
```

and the result are as follows:

```
[02/03/2023 16:43:05] {test_reader_simple.py:173} INFO - Total number of example 136
[02/03/2023 16:43:05] {test_reader_simple.py:174} INFO - {
  "bleu": 32.77
}
```

which has a gap with what you showed in Table 3 from your paper. Could help me how to reproduce your result(your result is 36.22 in your paper(codeT5+DocPrompting)).

Thanks a lot.

**Comment by JiexingQi** [comment]
By the way, could release more models mentioned in your paper, such as GPT-NEo?

**Comment by shuyanzhou** [comment]
Thanks for your interest!
> [02/03/2023 16:43:05] {test_reader_simple.py:173} INFO - Total number of example 136
There is a mismatch in the number of examples. The total number in the test set is 543. Did you modify the test file or break the evaluation earlier?

**Comment by JiexingQi** [comment]
Thanks for your reply, I didn't do any changes in your data file, And I just find a little bug in your code at /generator/fid/src/data.py
https://github.com/shuyanzhou/docprompting/blob/a239ec27d2870a6aa931621cc0949b2667f7306e/generator/fid/src/data.py#L122-L132

and you handle the data split in a multi-gpu fashion and I just use one GPU on my meachine to run evalution.

when I comment these two lines, things get normal

https://github.com/shuyanzhou/docprompting/blob/a239ec27d2870a6aa931621cc0949b2667f7306e/generator/fid/src/data.py#L131-L132

And the finally result I reproduce is 36.15,
```
[02/04/2023 10:16:58] {test_reader_simple.py:176} INFO - Total number of example 543
[02/04/2023 10:16:58] {test_reader_simple.py:177} INFO - {
  "bleu": 36.15
}
```

Thanks again. @shuyanzhou

**Comment by JiexingQi** [comment]
Another solution is just set the visible GPU numbers to 1. such as :
```
CUDA_VISIBLE_DEVICES="0" python generator/fid/test_reader_simple.py \
    --model_path models/generator/${ds}.fid.codet5.top10/checkpoint/best_dev/best_dev \
    --tokenizer_name models/generator/codet5-base \
    --eval_data data/${ds}/fid.cmd_test.codet5.t10.json \
    --per_gpu_batch_size 8 \
    --n_context 10 \
    --name ${ds}.fid.codet5.top10 \
    --checkpoint_dir models/generator  \
    --result_tag test_same \
    --main_port 81692
```

**Comment by shuyanzhou** [comment]
> By the way, could release more models mentioned in your paper, such as GPT-NEo?

@JiexingQi they are up! Check out the README

**Comment by JiexingQi** [comment]
Thank you a lot.
